version: '3.8'

services:
  mysql:
    image: mariadb:10.7.3
    restart: unless-stopped
    container_name: mysql-ewi
    environment:
      - MYSQL_DATABASE=ewidb
      - MYSQL_USER=ewiuser
      - MYSQL_PASSWORD=ewiuser_password
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_ROOT_HOST=ewi
  ewi:
    build: .
    container_name: ewi
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-ewi:3306/ewidb
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.username=ewiuser
      - spring.datasource.password=ewiuser_password
      - spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
      - myUser=admin
      - myPassword=admin
    depends_on:
      - mysql