version: '3.8'

services:
  mysql:
    image: mariadb:10.7.3
    restart: unless-stopped
    container_name: mysql-ewi
    env_file:
      - .db-env
  ewi:
    build: .
    container_name: ewi
    restart: unless-stopped
    ports:
      - "80:8080"
    env_file:
      - .app-env
    depends_on:
      - mysql